# Generated by Django 4.2 on 2023-04-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='purpose',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Place order', 'Place order'), ('Return', 'Return')], max_length=50),
        ),
    ]
